### ISSUE TITLE
hyper-parameters change

### ISSUE THREAD

**Issue by Ryan-Wu-13** [antoyang/TubeDETR#10]
Thank you for your work！
How do you determine the hyper-parameters of epochs=20 and batchsize=16 used for training on the hcstvg2.0 dataset? Does changing these parameters have a big impact on performance? Have you tried experimental results with longer epochs?

**Comment by antoyang** [comment]
I did all experiments on 16 GPUs (with batch size 1 per GPU) that's why I used batch size 16 on all datasets. For HC-STVG2.0, in initial experiments I tried training for up to 30 epochs but observed a saturation of the results between the last 10 epochs, hence the choice of 20 epochs in later experiments.

**Comment by Ryan-Wu-13** [comment]
Thank you for your reply, do you have the training log of the model hcstvgv2k4res352.pth, could you provide me with it for reference?

**Comment by Ryan-Wu-13** [comment]
@antoyang 
Thank you for your reply, 
do you have the training log of the model hcstvgv2k4res352.pth, could you provide me with it for reference?

**Comment by antoyang** [comment]
I did not keep the training log, but I put the test log stats for this model here https://drive.google.com/file/d/1lACP-bBb6mwpv00et7tqEdsWq633QSMv/view
